include:
  - docker-compose.infra.yml
  - docker-compose.migrations.yml
  - docker-compose.workers.yml

services:
  arb:
    image: iadzhak/arb-arb
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arb.rule=Host(`arbcrypto.ru`) && PathPrefix(`/api/arb/`)"
      - "traefik.http.routers.arb.entrypoints=websecure"
      - "traefik.http.services.arb.loadbalancer.server.port=80"

  auth:
    image: iadzhak/arb-auth
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`arbcrypto.ru`) && PathPrefix(`/api/auth/`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.services.auth.loadbalancer.server.port=80"

  frontend:
    image: iadzhak/arb-frontend
    volumes:
      - ./docs:/usr/share/nginx/html/docs:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`arbcrypto.ru`) && PathPrefix(`/`) && !PathPrefix(`/api/auth/`) && !PathPrefix(`/api/arb/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.tls.certresolver=le"